import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateCenso9B() {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const logoCenso = "/img/CensoEducativoLogo.png"; 

  const styles = {
    head: { fillColor: [230, 230, 230], textColor: 0, fontStyle: "bold", halign: "center", valign: "middle", lineWidth: 0.1, lineColor: 150, fontSize: 5, cellPadding: 0.5 },
    body: { textColor: 0, lineWidth: 0.1, lineColor: 150, fontSize: 5, valign: "middle", halign: "center", cellPadding: 0.5 },
    titleBox: { fillColor: [210, 210, 210], textColor: 0, fontStyle: "bold", fontSize: 7 }
  };

  const d = {
    codMod: "0240069", codLoc: "441744", cetpro: "CENTRO DE EDUCACIÓN TÉCNICO PRODUCTIVA PUNO", dist: "PUNO", loc: "PUNO",
    t101: [["TOTAL", "418", "875", "215", "480", "0", "0", "203", "395", "0", "0"], ["Aprobados", "395", "849", "200", "469", "0", "0", "195", "380", "0", "0"], ["Desaprobados", "1", "0", "1", "0", "0", "0", "0", "0", "0", "0"], ["Retirados", "22", "26", "14", "11", "0", "0", "8", "15", "0", "0"]],
    t102: [["TOTAL", "22", "26", "14", "11", "0", "0", "8", "15", "0", "0"]],
    t104: [["TOTAL", "395", "849", "200", "469", "0", "0", "195", "380", "0", "0"], ["Con Certificación", "170", "632", "97", "351", "0", "0", "73", "281", "0", "0"], ["Sin Certificación", "225", "217", "103", "118", "0", "0", "122", "99", "0", "0"]],
    t105_1: [["TOTAL", "215", "480", "0", "0", "203", "395", "0", "0", "14", "11", "0", "0", "8", "15", "0", "0"], ["ASISTENCIA EN COCINA", "31", "69", "0", "0", "34", "54", "0", "0", "2", "0", "0", "0", "1", "0", "0", "0"], ["MANUALIDADES", "0", "67", "0", "0", "0", "38", "0", "0", "0", "3", "0", "0", "0", "2", "0", "0"], ["ELECTRICIDAD", "31", "2", "0", "0", "24", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"], ["ELECTRÓNICA", "26", "6", "0", "0", "28", "0", "0", "0", "2", "0", "0", "0", "0", "0", "0", "0"], ["CONSTRUCCIONES METÁLICAS", "19", "0", "0", "0", "20", "0", "0", "0", "1", "0", "0", "0", "0", "0", "0", "0"], ["MECÁNICA AUTOMOTRIZ", "25", "0", "0", "0", "24", "2", "0", "0", "4", "0", "0", "0", "0", "0", "0", "0"], ["ASISTENCIA DE PANADERÍA", "16", "90", "0", "0", "20", "85", "0", "0", "0", "4", "0", "0", "1", "3", "0", "0"], ["CONFECCIÓN TEXTIL", "16", "105", "0", "0", "18", "95", "0", "0", "3", "2", "0", "0", "6", "7", "0", "0"], ["CARPINTERÍA", "27", "5", "0", "0", "28", "7", "0", "0", "1", "0", "0", "0", "0", "0", "0", "0"], ["OTROS", "18", "4", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"], ["PELUQUERÍA", "5", "101", "0", "0", "7", "78", "0", "0", "0", "1", "0", "0", "1", "1", "0", "0"], ["TEJIDO A MÁQUINA", "1", "31", "0", "0", "0", "36", "0", "0", "1", "1", "0", "0", "0", "1", "0", "0"]],
    t105_2: [["TOTAL", "200", "469", "0", "0", "177", "380", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"], ["CONFECCIÓN TEXTIL", "13", "103", "0", "0", "12", "88", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"], ["CARPINTERÍA", "26", "5", "0", "0", "28", "7", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"], ["OTROS", "18", "4", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"], ["PELUQUERÍA", "4", "100", "0", "0", "6", "77", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"], ["TEJIDO A MÁQUINA", "0", "30", "0", "0", "0", "35", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"]],
    t106: [["TOTAL", "377", "849", ...Array(26).fill("0"), "377", "849"], ["ASISTENCIA EN COCINA", "63", "122", ...Array(26).fill("0"), "63", "122"], ["MANUALIDADES", "0", "100", ...Array(26).fill("0"), "0", "100"], ["ELECTRICIDAD", "55", "2", ...Array(26).fill("0"), "55", "2"], ["ELECTRÓNICA", "52", "6", ...Array(26).fill("0"), "52", "6"], ["CONSTRUCCIONES METÁLICAS", "20", "0", ...Array(26).fill("0"), "20", "0"], ["MECÁNICA AUTOMOTRIZ", "45", "2", ...Array(26).fill("0"), "45", "2"], ["ASISTENCIA DE PANADERÍA", "35", "168", ...Array(26).fill("0"), "35", "168"], ["CONFECCIÓN TEXTIL", "25", "191", ...Array(26).fill("0"), "25", "191"], ["CARPINTERÍA", "54", "12", ...Array(26).fill("0"), "54", "12"], ["OTROS", "18", "4", ...Array(26).fill("0"), "18", "4"], ["PELUQUERÍA", "10", "177", ...Array(26).fill("0"), "10", "177"], ["TEJIDO A MÁQUINA", "0", "65", ...Array(26).fill("0"), "0", "65"]],
    t107: [["TOTAL", "0", "0", ...Array(28).fill("0")]],
    programas: [["01", "CTE0111458", "COSMETOLOGÍA", "400", "0", "1", "0", "0"], ["02", "CTE4131303", "LOGÍSTICA Y ALMACENES", "400", "0", "1", "1", "1"], ["03", "CTE6111399", "OPERACIÓN DE COMPUTADORAS", "400", "0", "1", "1", "1"], ["04", "CTE9X24014", "ESTILISMO", "528", "21", "0", "0", "0"]],
    sedesAT: [["01", "AT01", "PUNO CERCADO", "", "X", "", "210101", "PUNO", "PUNO", "PUNO", "JIRON CONDE DE LEMUS 138"], ["02", "AT02", "SALCEDO", "", "X", "", "210101", "PUNO", "PUNO", "PUNO", "S/N"], ["03", "AT03", "JALLUHUAYA", "", "X", "", "210101", "PUNO", "PUNO", "PUNO", "S/N"]],
    sedesTE: [["01", "TE01", "PUNO CERCADO", "", "X", "", "210101", "PUNO", "PUNO", "PUNO", "JIRON CONDE DE LEMUS 138"]],
    matriculaEdad: [["30-34", "21", "34", "7", "21", "14", "13"], ["19", "11", "15", "7", "9", "4", "6"], ["50-54", "20", "40", "13", "28", "7", "12"], ["23", "10", "32", "7", "17", "3", "15"], ["TOTAL", "239", "488", "137", "300", "102", "188"]],
    personal: [["01", "CALDERON MUNOZ ALENA MONICA", "01258974", "01", "50 Mujer", "0100", "307", "01", "01", "01", "05", "02", "25", "25", "25", "06", "01", "01", "03", "40"], ["02", "TAPIA COAQUIRA JOSE", "01308555", "01", "56 Hombr", "0100", "", "01", "01", "01", "02", "03", "29", "01", "31", "31", "16", "08", "13", "", "01", "40"], ["03", "COA RIVAS IMELDA TERESA", "02144514", "01", "63 Mujer", "0100", "3342", "01", "01", "01", "02", "02", "", "02", "33", "33", "33", "04", "13", "", "03", "40"]]
  };

  try { doc.addImage(logoCenso, "PNG", 15, 8, 25, 15); } catch (e) {}
  doc.setFont("helvetica", "bold"); doc.setFontSize(10); doc.text("2024", 105, 12, { align: "center" });
  doc.setFontSize(14); doc.text("CENSO EDUCATIVO", 105, 17, { align: "center" });
  doc.setFontSize(9); doc.text("RESULTADO DEL EJERCICIO EDUCATIVO", 105, 22, { align: "center" });
  doc.setFontSize(35); doc.setTextColor(40, 40, 40); doc.text("9B", 195, 18, { align: "right" }); doc.setTextColor(0);
  doc.setFillColor(230, 230, 230); doc.rect(145, 24, 50, 6, "F"); 
  doc.setFontSize(7); doc.setFont("helvetica", "italic"); doc.text("CONSTANCIA DE ENVIO Nº", 143, 28, { align: "right" });
  doc.setFont("helvetica", "bold"); doc.text("252895", 170, 28, { align: "center" });
  doc.setFont("helvetica", "italic"); doc.text("FECHA DE ENVIO :", 143, 33, { align: "right" }); doc.setFont("helvetica", "normal"); doc.text("21/02/25 04:27 PM", 148, 33);

  const marginX = 15; const width = 180; const startY = 37; 
  doc.setFillColor(210, 210, 210); doc.setDrawColor(150); doc.setLineWidth(0.1); doc.rect(marginX, startY, width, 5, "FD");
  doc.setFont("helvetica", "bold"); doc.setFontSize(7); doc.text("IDENTIFICACIÓN DE LA SERVICIO EDUCATIVO", 105, startY + 3.5, { align: "center" });
  const dataBoxY = startY + 6.5; 
  doc.setFillColor(210, 210, 210); doc.rect(marginX, dataBoxY, width, 22, "FD");

  const drawInput = (label, value, xLabel, yPos, wInput, xInputOffset) => { doc.setFont("helvetica", "normal"); doc.setFontSize(7); doc.setTextColor(0); doc.text(label, xLabel, yPos + 3); doc.setFillColor(255); doc.rect(xLabel + xInputOffset, yPos, wInput, 4.5, "F"); doc.setFont("helvetica", "bold"); doc.text(value, xLabel + xInputOffset + 2, yPos + 3); doc.setFont("helvetica", "normal"); };
  let cursorY = dataBoxY + 2; 
  drawInput("1. CÓDIGO MODULAR:", d.codMod, marginX + 2, cursorY, 35, 30); drawInput("2. CÓDIGO DE LOCAL EDUCATIVO:", d.codLoc, marginX + 85, cursorY, 35, 50);
  cursorY += 6; drawInput("2. NOMBRE DEL", d.cetpro, marginX + 2, cursorY, 138, 30);
  cursorY += 6; drawInput("4. DISTRITO", d.dist, marginX + 2, cursorY, 55, 30); drawInput("LOCALIDAD :", d.loc, marginX + 105, cursorY, 40, 25);

  const resY = dataBoxY + 25;
  doc.setFillColor(225); doc.setDrawColor(100); doc.rect(marginX, resY, width, 5, "FD");
  doc.setFont("helvetica", "bold"); doc.setFontSize(7.5); doc.text("100. RESULTADO DEL EJERCICIO EDUCATIVO", 105, resY + 3.5, { align: "center" });
  doc.setFontSize(6.5); doc.text("101. SITUACIÓN DEL EJERCICIO EDUCATIVO, POR SEMESTRE, CICLO Y SEXO", marginX, resY + 9);

  autoTable(doc, { startY: resY + 11, head: [[{ content: "SITUACIÓN", rowSpan: 3, styles: styles.head }, { content: "TOTAL", colSpan: 2, rowSpan: 2, styles: styles.head }, { content: "SEMESTRE - I", colSpan: 4, styles: styles.head }, { content: "SEMESTRE - II", colSpan: 4, styles: styles.head }], [{ content: "Auxiliar\nTécnico", colSpan: 2, styles: styles.head }, { content: "Técnico", colSpan: 2, styles: styles.head }, { content: "Auxiliar\nTécnico", colSpan: 2, styles: styles.head }, { content: "Técnico", colSpan: 2, styles: styles.head }], [{ content: "H", styles: styles.head }, { content: "M", styles: styles.head }, { content: "H", styles: styles.head }, { content: "M", styles: styles.head }, { content: "H", styles: styles.head }, { content: "M", styles: styles.head }, { content: "H", styles: styles.head }, { content: "M", styles: styles.head }, { content: "H", styles: styles.head }, { content: "M", styles: styles.head }]], body: d.t101, theme: 'grid', headStyles: styles.head, bodyStyles: styles.body, columnStyles: { 0: { cellWidth: 35, halign: 'left' } }, margin: { left: marginX, right: 15 } });
  
  let fY = doc.lastAutoTable.finalY + 5; doc.setFont("helvetica", "bold"); doc.text("102. RETIRADOS POR CICLO Y SEXO; SEGÚN MOTIVO", marginX, fY);
  autoTable(doc, { startY: fY + 1, head: [[{ content: "MOTIVO", rowSpan: 3, styles: styles.head }, { content: "TOTAL", colSpan: 2, rowSpan: 2, styles: styles.head }, { content: "SEMESTRE - I", colSpan: 4, styles: styles.head }, { content: "SEMESTRE - II", colSpan: 4, styles: styles.head }], [{ content: "Auxiliar\nTécnico", colSpan: 2, styles: styles.head }, { content: "Técnico", colSpan: 2, styles: styles.head }, { content: "Auxiliar\nTécnico", colSpan: 2, styles: styles.head }, { content: "Técnico", colSpan: 2, styles: styles.head }], ["H", "M", "H", "M", "H", "M", "H", "M", "H", "M"]], body: d.t102, theme: 'grid', headStyles: styles.head, bodyStyles: styles.body, columnStyles: { 0: { cellWidth: 35, halign: 'left' } }, margin: { left: marginX, right: 15 } });
  fY = doc.lastAutoTable.finalY + 5; doc.text("103. DESCRIPCIÓN DE OTROS", marginX, fY);
  autoTable(doc, { startY: fY + 1, head: [["NRO.", "Otra enfermedad", "Otro tipo de adicción", "Otros motivo de retiro"]], body: [["", "", "", ""]], theme: 'grid', headStyles: styles.head, bodyStyles: { ...styles.body, minCellHeight: 6 }, margin: { left: marginX, right: 15 }});

  doc.addPage(); let p2Y = 15;
  doc.setFont("helvetica", "bold"); doc.text("104. APROBADOS CON CERTIFICACIÓN Y SIN CERTIFICACIÓN POR CICLO Y SEXO", marginX, p2Y);
  autoTable(doc, { startY: p2Y + 2, head: [[{ content: "SITUACIÓN", rowSpan: 3, styles: styles.head }, { content: "TOTAL", colSpan: 2, rowSpan: 2, styles: styles.head }, { content: "SEMESTRE - I", colSpan: 4, styles: styles.head }, { content: "SEMESTRE - II", colSpan: 4, styles: styles.head }], [{ content: "Auxiliar\nTécnico", colSpan: 2, styles: styles.head }, { content: "Técnico", colSpan: 2, styles: styles.head }, { content: "Auxiliar\nTécnico", colSpan: 2, styles: styles.head }, { content: "Técnico", colSpan: 2, styles: styles.head }], [{ content: "H", styles: styles.head }, { content: "M", styles: styles.head }, { content: "H", styles: styles.head }, { content: "M", styles: styles.head }, { content: "H", styles: styles.head }, { content: "M", styles: styles.head }, { content: "H", styles: styles.head }, { content: "M", styles: styles.head }, { content: "H", styles: styles.head }, { content: "M", styles: styles.head }]], body: d.t104, theme: 'grid', headStyles: styles.head, bodyStyles: styles.body, columnStyles: { 0: { cellWidth: 35, halign: 'left' } }, margin: { left: marginX, right: 15 } });

  p2Y = doc.lastAutoTable.finalY + 8; doc.setFontSize(7); doc.setFont("helvetica", "bold"); doc.text("105. MATRÍCULADOS, RETIRADOS, EGRESADOS Y TITULADOS EN 2024, POR SEMESTRE ACADÉMICO Y SEXO, SEGÚN", marginX, p2Y); doc.text("DENOMINACIÓN DE LA OPCIÓN OCUPACIONAL", marginX, p2Y + 4);
  const head105 = [[{ content: "OPCIÓN OCUPACIONAL", rowSpan: 2, styles: styles.head }, { content: "MATRICULADOS", colSpan: 8, styles: styles.head }, { content: "RETIRADOS", colSpan: 8, styles: styles.head }], [{ content: "SEMESTRE 2023 - I", colSpan: 4, styles: styles.head }, { content: "SEMESTRE 2023 - II", colSpan: 4, styles: styles.head }, { content: "SEMESTRE 2023 - I", colSpan: 4, styles: styles.head }, { content: "SEMESTRE 2023 - II", colSpan: 4, styles: styles.head }], [{ content: "DENOMINACIÓN", styles: styles.head }, { content: "Auxiliar\nTécnico", colSpan: 2, styles: styles.head }, { content: "Técnico", colSpan: 2, styles: styles.head }, { content: "Auxiliar\nTécnico", colSpan: 2, styles: styles.head }, { content: "Técnico", colSpan: 2, styles: styles.head }, { content: "Auxiliar\nTécnico", colSpan: 2, styles: styles.head }, { content: "Técnico", colSpan: 2, styles: styles.head }, { content: "Auxiliar\nTécnico", colSpan: 2, styles: styles.head }, { content: "Técnico", colSpan: 2, styles: styles.head }], [{ content: "", styles: { cellPadding: 0, fontSize: 1 } }, "H", "M", "H", "M", "H", "M", "H", "M", "H", "M", "H", "M", "H", "M", "H", "M"]];
  autoTable(doc, { startY: p2Y + 6, head: head105, body: d.t105_1, theme: 'grid', headStyles: { ...styles.head, fontSize: 4.5 }, bodyStyles: { ...styles.body, fontSize: 4.5, cellPadding: 1 }, columnStyles: { 0: { cellWidth: 40, halign: 'left' } }, margin: { left: marginX, right: 15 } });
  
  p2Y = doc.lastAutoTable.finalY + 8; doc.text("105. Continuación ...", marginX, p2Y);
  const head105Cont = [[{ content: "OPCIÓN OCUPACIONAL", rowSpan: 2, styles: styles.head }, { content: "EGRESADOS", colSpan: 8, styles: styles.head }, { content: "TITULADOS", colSpan: 8, styles: styles.head }], [{ content: "SEMESTRE 2023 - I", colSpan: 4, styles: styles.head }, { content: "SEMESTRE 2023 - II", colSpan: 4, styles: styles.head }, { content: "SEMESTRE 2023 - I", colSpan: 4, styles: styles.head }, { content: "SEMESTRE 2023 - II", colSpan: 4, styles: styles.head }], head105[2], head105[3]];
  autoTable(doc, { startY: p2Y + 2, head: head105Cont, body: d.t105_2, theme: 'grid', headStyles: { ...styles.head, fontSize: 4.5 }, bodyStyles: { ...styles.body, fontSize: 4.5, cellPadding: 1 }, columnStyles: { 0: { cellWidth: 40, halign: 'left' } }, margin: { left: marginX, right: 15 } });

  doc.addPage(); let p3Y = 15;
  doc.setFontSize(7); doc.setFont("helvetica", "bold"); doc.text("106. EGRESADOS POR SEXO, SEGÚN TIPO DE DISCAPACIDAD U OTRA CONDICIÓN EN LOS SEMESTRES 2024-I", marginX, p3Y);
  const headDisc = [[{ content: "CARRERAS Y/O\nPROGRAMAS DE\nESTUDIOS", rowSpan: 2, styles: styles.head }, { content: "TOTAL", colSpan: 2, rowSpan: 2, styles: styles.head }, { content: "Discapacidad Intelectual", colSpan: 6, styles: styles.head }, { content: "Discapacidad\nAuditiva", colSpan: 4, styles: styles.head }, { content: "Discapacidad\nVisual", colSpan: 4, styles: styles.head }, { content: "Disca-\nparcidad\nFísica o\nMotora", colSpan: 2, styles: styles.head }, { content: "Trans-\ntorno del\nEspectro\nAutista", colSpan: 2, styles: styles.head }, { content: "Sordo\nceguera", colSpan: 2, styles: styles.head }, { content: "Multi\ndiscapa\ncidad", colSpan: 2, styles: styles.head }, { content: "Otra\ndiscapa\ncidad u\notra\ncondición", colSpan: 2, styles: styles.head }, { content: "No tiene\ndiscapacidad u\notra condición", colSpan: 2, styles: styles.head }], [{ content: "Leve", colSpan: 2, styles: styles.head }, { content: "Moderada", colSpan: 2, styles: styles.head }, { content: "Severa", colSpan: 2, styles: styles.head }, { content: "Hipo-\nacusia", colSpan: 2, styles: styles.head }, { content: "Sordera", colSpan: 2, styles: styles.head }, { content: "Baja visión", colSpan: 2, styles: styles.head }, { content: "Ceguera", colSpan: 2, styles: styles.head }, { content: "", colSpan: 2, styles: styles.head }, { content: "", colSpan: 2, styles: styles.head }, { content: "", colSpan: 2, styles: styles.head }, { content: "", colSpan: 2, styles: styles.head }, { content: "", colSpan: 2, styles: styles.head }, { content: "", colSpan: 2, styles: styles.head }], ["DENOMINACIÓN", ...Array(28).fill("").map((_, i) => i % 2 === 0 ? "H" : "M")]];
  autoTable(doc, { startY: p3Y + 2, head: headDisc, body: d.t106, theme: 'grid', headStyles: { ...styles.head, fontSize: 4, cellPadding: 0.5 }, bodyStyles: { ...styles.body, fontSize: 4, cellPadding: 0.5 }, columnStyles: { 0: { cellWidth: 25, halign: 'left' } }, margin: { left: marginX, right: 5 } });
  
  let y107 = doc.lastAutoTable.finalY + 8; doc.text("107. TITULADOS POR SEXO, SEGÚN TIPO DE DISCAPACIDAD U OTRA CONDICIÓN EN LOS SEMESTRES 2024-I", marginX, y107);
  autoTable(doc, { startY: y107 + 2, head: headDisc, body: d.t107, theme: 'grid', headStyles: { ...styles.head, fontSize: 4, cellPadding: 0.5 }, bodyStyles: { ...styles.body, fontSize: 4, cellPadding: 0.5 }, columnStyles: { 0: { cellWidth: 25, halign: 'left' } }, margin: { left: marginX, right: 5 } });
  let y108 = doc.lastAutoTable.finalY + 8; doc.text("108. ¿CUÁNTOS ESTUDIANTES QUE INGRESARON A ESTA INSTITUCIÓN EN EL CICLO/MÓDULO I DEL PERIODO 2024, SON", marginX, y108); doc.text("EGRESADOS DEL 5º AÑO DE EDUCACIÓN SECUNDARIA DEL PERÍODO 2023, PARA AUXILIAR TÉCNICO Y TÉCNICO?", marginX, y108 + 3); doc.line(marginX, y108 + 6, marginX + width, y108 + 6);

  doc.addPage(); let p4Y = 15;
  doc.setFillColor(...styles.titleBox.fillColor); doc.rect(marginX, p4Y, width, 5, "FD"); doc.setFontSize(7); doc.text("OPCIONES OCUPACIONALES Y/O PROGRAMAS DE ESTUDIO", 105, p4Y + 3.5, { align: "center" });
  autoTable(doc, { startY: p4Y + 5, head: [[{ content: "N°", rowSpan: 2, styles: styles.head }, { content: "CÓDIGO", rowSpan: 2, styles: styles.head }, { content: "DENOMINACIÓN", rowSpan: 2, styles: styles.head }, { content: "DURACIÓN", colSpan: 2, styles: styles.head }, { content: "NÚMERO DE SECCIONES", colSpan: 3, styles: styles.head }],[ "Número de\nhoras", "Número de\ncréditos", "Mañana", "Tarde", "Noche" ]], body: d.programas, theme: 'grid', headStyles: styles.head, bodyStyles: styles.body, columnStyles: { 2: { halign: 'left' } }, margin: { left: marginX, right: 15 } });
  p4Y = doc.lastAutoTable.finalY + 6; doc.text("UBICACIÓN GEOGRÁFICA DE LAS SEDES", marginX, p4Y);
  const geoHeader = [[{ content: "N°", rowSpan: 3, styles: styles.head }, { content: "CÓDIGO\nDE LA\nSEDE", rowSpan: 3, styles: styles.head }, { content: "NOMBRE DE LA SEDE", rowSpan: 3, styles: styles.head }, { content: "¿Se encuentra\nlicenciada?", colSpan: 3, styles: styles.head }, { content: "UBICACIÓN GEOGRÁFICA", colSpan: 5, styles: styles.head } ], [{ content: "Sí", rowSpan: 2, styles: styles.head }, { content: "No", colSpan: 2, styles: styles.head }, { content: "CÓDIGO", rowSpan: 2, styles: styles.head }, { content: "DEPARTA\nMENTO", rowSpan: 2, styles: styles.head }, { content: "PROVINCIA", rowSpan: 2, styles: styles.head }, { content: "DISTRITO", rowSpan: 2, styles: styles.head }, { content: "DIRECCIÓN", rowSpan: 2, styles: styles.head } ], [{ content: "", styles: { minCellWidth: 5, minCellHeight: 25 } }, { content: "", styles: { minCellWidth: 5, minCellHeight: 25 } }]];
  const drawVerticalGeo = (data) => { if (data.section === 'head' && data.row.index === 2) { let text = ""; if (data.column.index === 4) text = "En\nproceso"; if (data.column.index === 5) text = "Sin\nempezar"; if (text) { const { x, y, width, height } = data.cell; doc.setFontSize(4.5); doc.setTextColor(0); doc.text(text, x + width / 2 + 1.2, y + height - 3, { angle: 90 }); }}};
  autoTable(doc, { startY: p4Y + 2, head: geoHeader, body: d.sedesAT, theme: 'grid', headStyles: styles.head, bodyStyles: styles.body, columnStyles: { 2: { halign: 'left', cellWidth: 35 }, 10: { halign: 'left', cellWidth: 35 } }, margin: { left: marginX, right: 15 }, didDrawCell: drawVerticalGeo });
  autoTable(doc, { startY: doc.lastAutoTable.finalY + 5, head: geoHeader, body: d.sedesTE, theme: 'grid', headStyles: styles.head, bodyStyles: styles.body, columnStyles: { 2: { halign: 'left', cellWidth: 35 }, 10: { halign: 'left', cellWidth: 35 } }, margin: { left: marginX, right: 15 }, didDrawCell: drawVerticalGeo });
  p4Y = doc.lastAutoTable.finalY + 10; doc.setFillColor(225); doc.rect(marginX, p4Y, width, 5, "FD"); doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.text("200. MATRÍCULA Y SECCIONES", 105, p4Y + 3.5, { align: "center" }); doc.setFontSize(7); doc.text("201. MATRÍCULA POR CICLOS Y SEXO, SEGÚN EDAD", marginX, p4Y + 9);
  autoTable(doc, { startY: p4Y + 11, head: [[ { content: "Edad en años cumplidos al\n31-03-2023", rowSpan: 2, styles: styles.head }, { content: "TOTAL", colSpan: 2, styles: styles.head }, { content: "CICLO", colSpan: 4, styles: styles.head } ],[ "H", "M", { content: "Auxiliar", colSpan: 2 }, { content: "Técnico", colSpan: 2 } ]], body: d.matriculaEdad, theme: 'grid', headStyles: styles.head, bodyStyles: styles.body, margin: { left: marginX, right: 15 } });
  let y208 = doc.lastAutoTable.finalY; doc.text("208. NÚMERO TOTAL DE SECCIONES POR CICLO, SEGÚN TURNO", marginX, y208 + 6);
  autoTable(doc, { startY: y208 + 8, head: [[ { content: "TURNO", rowSpan: 2 }, { content: "TOTAL\nSECCIONES", rowSpan: 2 }, { content: "CICLO", colSpan: 2 } ],["Auxiliar", "Técnico"]], body: [["Noche", "11", "7", "4"], ["Total", "31", "20", "11"], ["Tarde", "9", "6", "3"], ["Mañana", "11", "7", "4"]], theme: 'grid', headStyles: styles.head, bodyStyles: styles.body, tableWidth: 100, margin: { left: marginX } });

  doc.addPage(); let p5Y = 15; doc.setFillColor(225); doc.rect(marginX, p5Y, width, 5, "FD"); doc.setFont("helvetica", "bold"); doc.setFontSize(8); doc.text("300. PERSONAL DOCENTE Y ADMINISTRATIVO", 105, p5Y + 3.5, { align: "center" }); doc.setFontSize(7); doc.text("TOTALES    Docentes:  29     Docentes de aula:   0      Auxiliares de aula:  0      Administrativos:   8", marginX, p5Y + 9);
  autoTable(doc, { startY: p5Y + 12, head: [[ "N°", "Apellidos y Nombres", "DNI/CE", "303", "304", "305", "306", "307", "308", "309", "310", "311", "312", "313", "314", "315", "316", "317", "318", "319", "320" ]], body: d.personal, theme: 'grid', headStyles: { ...styles.head, fontSize: 5, padding: 0 }, bodyStyles: { ...styles.body, fontSize: 5, padding: 0.5 }, columnStyles: { 1: { cellWidth: 40, halign: 'left' } }, margin: { left: marginX, right: 15 } });
  let finalY5 = doc.internal.pageSize.height - 40; doc.setDrawColor(0); doc.line(marginX, finalY5, marginX + width, finalY5); doc.setFontSize(8); doc.setFont("helvetica", "bold"); doc.text("DATOS DEL DIRECTOR/RESPONSABLE DEL LLENADO DE LA CÉDULA", 105, finalY5 - 3, { align: "center" });
  doc.text("NOMBRES Y APELLIDOS", marginX, finalY5 + 5); doc.text("CARGO", marginX + 60, finalY5 + 5); doc.text("CORREO ELECTRÓNICO", marginX + 110, finalY5 + 5); doc.text("TELÉFONO", marginX + 160, finalY5 + 5);
  doc.line(marginX, finalY5 + 7, marginX + width, finalY5 + 7); doc.setFont("helvetica", "normal"); doc.text("JOSE TAPIA COAQUIRA", marginX, finalY5 + 12); doc.text("COORDINADOR(A)", marginX + 60, finalY5 + 12); doc.text("josetapia@cetpropuno.edu.pe", marginX + 110, finalY5 + 12); doc.text("961522899", marginX + 160, finalY5 + 12); doc.line(marginX, finalY5 + 15, marginX + width, finalY5 + 15);

  const pdfBlob = doc.output("blob");
  window.open(URL.createObjectURL(pdfBlob), "_blank");
}